import type { Metadata } from 'next';
import './globals.css';

import { fonts } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Mocca Cafe | Ứng dụng đặt mua Cafe đa dạng',
  description: 'Generated by Mocca Cafe',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const resolvedParams = await params;
  const { locale } = resolvedParams;

  return (
    <html lang={locale}>
      <body className={`${fonts.lora} antialiased`}>{children}</body>
    </html>
  );
}
